apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: postgres-cdc
  namespace: confluent
spec:
  class: "io.debezium.connector.postgresql.PostgresConnector"
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    plugin.name: pgoutput
    topic.prefix: "pg"
    tasks.max: "1"
    database.hostname: "<DB_HOSTNAME>"
    database.port: "5432"
    database.user: "<DB_USERNAME>"
    database.password: "<DB_PASS>"
    database.dbname: "postgres"
    output.data.format: JSON
    publication.autocreate.mode: "all_tables"
    "publication.name": "dbz_publication"
    "slot.name": "debezium_new"
    topic.creation.enable: "true"
    topic.creation.default.replication.factor: "3"
    topic.creation.default.partitions: "3"
    topic.creation.default.cleanup.policy: "delete"
  
