apiVersion: platform.confluent.io/v1beta1
kind: FlinkApplication
metadata:
  name: flink-app
  namespace: confluent
spec:
  flinkEnvironment: flink-env
  image: confluentinc/cp-flink:1.19.1-cp2
  flinkVersion: v1_19
  flinkConfiguration:
    "taskmanager.numberOfTaskSlots": "2"
    "metrics.reporter.prom.factory.class": "org.apache.flink.metrics.prometheus.PrometheusReporterFactory"
    "metrics.reporter.prom.port": "9249-9250"
    "rest.profiling.enabled": "true"
  serviceAccount: flink
  flinkConfiguration:
    fs.azure.enabled: "true"
    state.checkpoints.dir: wasbs://<container>@<storage-account>.blob.core.windows.net/checkpoint/
    fs.azure.account.key.<storage-account>.blob.core.windows.net: <azure-access-key>
    execution.checkpointing.interval: "30"
    execution.checkpoint.mode: EXACTLY_ONCE

    state.backend: rocksdb
    state.backend.incremental: "true"
    state.backend.rocksdb.localdir: /localstatedir

  podTemplate:
    spec:
      containers:
          - name: flink-main-container
            env:
              - name: ENABLE_BUILT_IN_PLUGINS
                value: "flink-azure-fs-hadoop-1.19.1-cp2.jar"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app-confluent
                    operator: In
                    values:
                      - taskmanager
  jobManager:
    resource:
      memory: 1048m
      cpu: 1
  taskManager:
    replicas: 3
    podTemplate:
      spec:
        volumes:
          - name: rocksdb-storage
            emptyDir: {}
        containers:
          - name: flink-main-container
            volumeMounts:
              - name: rocksdb-storage
                mountPath: /localstatedir
    resource:
      memory: 1048m
      cpu: 1
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    state: running
    parallelism: 3
    upgradeMode: stateless
  cmfRestClassRef:
    name: default
    namespace: confluent
