apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-demo-source
  namespace: confluent
spec:
  name: clusterlink-demo
  sourceInitiatedLink:
    linkMode: Source
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
    authentication:
      type: plain
      jaasConfigPassThrough:
        secretRef: jaasconfig-ccloud
    tls:
      enabled: true
      #secretRef: ccloud-tls-certs
    bootstrapEndpoint: pkc-5w9qrq.us-east-2.aws.confluent.cloud:9092
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
  mirrorTopics:
    - name: demo-topic
